In [3]:
import numpy as np

In [5]:
arr = np.array([1,2])

In [15]:
arr

array([1, 2])

In [17]:
np.arange(0,11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [19]:
np.zeros(2)

array([0., 0.])

In [21]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [25]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [29]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [35]:
np.random.rand(4)

array([0.1009636 , 0.09537904, 0.35898051, 0.42627422])

In [37]:
np.random.randn(4)

array([-0.85372749,  0.08256894, -0.76026451, -0.81459212])

In [41]:
np.random.randint(0,10,5)

array([3, 0, 9, 1, 3])

In [43]:
rarr = np.arange(25)

In [45]:
print(rarr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [47]:
rarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [51]:
rarr.max()

24

In [53]:
rarr.argmax()

24

In [57]:
rarr.argmin()

0

In [65]:
rarr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [67]:
rarr.shape

(25,)

In [83]:
np.random.rand(30)

array([3.94119343e-01, 2.87774294e-01, 8.42374934e-01, 2.73764310e-01,
       9.12127921e-01, 6.28118111e-01, 1.52676837e-01, 5.80758668e-01,
       3.97874849e-01, 8.10740932e-02, 6.75674496e-03, 8.82158131e-01,
       2.76647871e-01, 1.43084736e-01, 6.09195728e-01, 5.28320097e-01,
       5.08147684e-04, 6.27567905e-01, 7.68945145e-01, 3.63661303e-01,
       6.60843730e-01, 8.66181366e-01, 7.25831661e-01, 6.96591839e-01,
       6.63705720e-01, 3.71437255e-01, 3.38887408e-01, 2.94979384e-01,
       4.36964417e-01, 2.24564637e-01])

In [85]:
list =[[1,2],[3,4],[5,6]]

In [89]:
np.array(list[0])

array([1, 2])

In [99]:
nr = np.arange(0,10)

In [101]:
nr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [103]:
nr[0:5]

array([0, 1, 2, 3, 4])

In [105]:
nr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [107]:
nr[-1]

9

In [109]:
nrr = nr.copy()

In [111]:
nrr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [113]:
nrr[0:4] = 77

In [115]:
nrr

array([77, 77, 77, 77,  4,  5,  6,  7,  8,  9])

In [117]:
nrr = np.array([[1,2],[3,4],[5,6]])

In [119]:
nrr

array([[1, 2],
       [3, 4],
       [5, 6]])

In [121]:
nrr[1][1]

4

In [125]:
nrr[2][1]

6

In [127]:
nrr[2,1]

6

In [161]:
p = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [163]:
p

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [169]:
p[:2,1:]

array([[10, 15],
       [25, 30]])

In [173]:
p = np.arange(0,10)

In [175]:
p

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
p>7

array([False, False, False, False, False, False, False, False,  True,
        True])

In [183]:
p[p>7]

array([8, 9])

In [185]:
c= np.arange(25).reshape(5,5)

In [187]:
c

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [207]:
c[2:4, 3:]

array([[13, 14],
       [18, 19]])

In [209]:
#Array Operations

In [211]:
arr = np.arange(0,10)

In [213]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [215]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [217]:
arr*arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [219]:
arr/arr

C:\Users\User\AppData\Local\Temp\ipykernel_17696\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [221]:
arr*15

array([  0,  15,  30,  45,  60,  75,  90, 105, 120, 135])